### PR TITLE
Add acceptance tests

### PR DESCRIPTION
**Pull request by jcscottiii**
Builds on #6 (merge that first)

Still need unit tests but at least we have some tests that use the real executable and tests the expected behavior.

Also, these tests don't use the `--global` flag.
# Features in this PR
- Use of Ginkgo
- Add tests, see below
# Tests added
## 1. Help

1) when no arguments are provided

```
  should show the help for the command
NAME:
   git-seekret - prevent from committing sensitive information into git repository

USAGE:
   git-seekret [global options] command [command options] [arguments...]

VERSION:
   0.0.1

AUTHOR(S):
   Albert Puigsech Galicia <albert@puigsech.com>

COMMANDS:
     config   manage configuration seetings
     rules    manage rules
     check    inspect git repository
     hook     manage git hooks
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --global
   --help, -h     show help
   --version, -v  print the version 
```

2) when the -h flag is provided

```
  should show the help for the command
NAME:
   git-seekret - prevent from committing sensitive information into git repository

USAGE:
   git-seekret [global options] command [command options] [arguments...]

VERSION:
   0.0.1

AUTHOR(S):
   Albert Puigsech Galicia <albert@puigsech.com>

COMMANDS:
     config   manage configuration seetings
     rules    manage rules
     check    inspect git repository
     hook     manage git hooks
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --global
   --help, -h     show help
   --version, -v  print the version
```
## 2. Config

1) when it has not been configured

```
  should show a warning that it has been configured
Config not initialised - Try: 'git-seekret config --init'
```

2) when it initialized to a config locally should create the config for the local config with defaults

```
have to skip beacuse we need a way to create the default path if it doesn't exist
```

Outlined in #8

3) when it initialized to a config locally
  should create the config for the local config with the rules in a custom location by supplying SEEKRET_RULES_PATH.

```
  /Users/jamesscott/Development/Workspaces/seekret-git-ws-fork/src/github.com/apuigsech/git-seekret/main_test.go:123
Initialized empty Git repository in /private/var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo588630123/.git/
STEP: creating the SEEKRET_RULES_PATH folder
STEP: setting the SEEKRET_RULES_PATH
STEP: calling the config --init and checking the output
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo154990798
        rulesenabled =
        exceptionsfile =
STEP: checking the local git config
STEP: calling config again, it should just print out the config again.
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo154990798
        rulesenabled =
        exceptionsfile =
```
## 3. Rules

1) should show nothing when there are no rules in the directory

```
  /Users/jamesscott/Development/Workspaces/seekret-git-ws-fork/src/github.com/apuigsech/git-seekret/main_test.go:137
Initialized empty Git repository in /private/var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo396310389/.git/
STEP: creating the SEEKRET_RULES_PATH folder
STEP: setting the SEEKRET_RULES_PATH
STEP: calling the config --init and checking the output
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo616228432
        rulesenabled =
        exceptionsfile =
STEP: checking the local git config
STEP: calling config again, it should just print out the config again.
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo616228432
        rulesenabled =
        exceptionsfile =
List of rules:
```

2) should allow for rules to be enabled

```
  /Users/jamesscott/Development/Workspaces/seekret-git-ws-fork/src/github.com/apuigsech/git-seekret/main_test.go:147
Initialized empty Git repository in /private/var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo697550201/.git/
STEP: creating the SEEKRET_RULES_PATH folder
STEP: setting the SEEKRET_RULES_PATH
STEP: calling the config --init and checking the output
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo396859524
        rulesenabled =
        exceptionsfile =
STEP: checking the local git config
STEP: calling config again, it should just print out the config again.
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo396859524
        rulesenabled =
        exceptionsfile =
List of rules:
        [ ] password.password
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
```

3) should allow for rules to be disabled

```
  /Users/jamesscott/Development/Workspaces/seekret-git-ws-fork/src/github.com/apuigsech/git-seekret/main_test.go:154
Initialized empty Git repository in /private/var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo671630867/.git/
STEP: creating the SEEKRET_RULES_PATH folder
STEP: setting the SEEKRET_RULES_PATH
STEP: calling the config --init and checking the output
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo589887574
        rulesenabled =
        exceptionsfile =
STEP: checking the local git config
STEP: calling config again, it should just print out the config again.
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo589887574
        rulesenabled =
        exceptionsfile =
List of rules:
        [ ] password.password
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
List of rules:
        [ ] password.pass
        [ ] password.cred
        [ ] password.password
        [ ] password.pwd
```
## 4. Check

1) when checking staged changes when there are no files

```
  should detect no violations
  /Users/jamesscott/Development/Workspaces/seekret-git-ws-fork/src/github.com/apuigsech/git-seekret/main_test.go:175
Initialized empty Git repository in /private/var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo773077949/.git/
STEP: creating the SEEKRET_RULES_PATH folder
STEP: setting the SEEKRET_RULES_PATH
STEP: calling the config --init and checking the output
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo233878008
        rulesenabled =
        exceptionsfile =
STEP: checking the local git config
STEP: calling config again, it should just print out the config again.
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo233878008
        rulesenabled =
        exceptionsfile =
List of rules:
        [ ] password.password
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
List of rules:
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
        [x] password.password
List of rules:
        [x] password.password
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
Found Secrets: 0
```

2) when checking staged changes when there is a staged file but with no violation

```
  should detect no violations
  /Users/jamesscott/Development/Workspaces/seekret-git-ws-fork/src/github.com/apuigsech/git-seekret/main_test.go:182
Initialized empty Git repository in /private/var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo177995511/.git/
STEP: creating the SEEKRET_RULES_PATH folder
STEP: setting the SEEKRET_RULES_PATH
STEP: calling the config --init and checking the output
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo931872746
        rulesenabled =
        exceptionsfile =
STEP: checking the local git config
STEP: calling config again, it should just print out the config again.
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo931872746
        rulesenabled =
        exceptionsfile =
List of rules:
        [ ] password.password
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
List of rules:
        [x] password.password
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
List of rules:
        [x] password.password
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
Found Secrets: 0
```

3) when checking staged changes when there is a staged file but with a violation

```
  should detect 1 violation
  /Users/jamesscott/Development/Workspaces/seekret-git-ws-fork/src/github.com/apuigsech/git-seekret/main_test.go:189
Initialized empty Git repository in /private/var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo726490689/.git/
STEP: creating the SEEKRET_RULES_PATH folder
STEP: setting the SEEKRET_RULES_PATH
STEP: calling the config --init and checking the output
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo374955180
        rulesenabled =
        exceptionsfile =
STEP: checking the local git config
STEP: calling config again, it should just print out the config again.
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo374955180
        rulesenabled =
        exceptionsfile =
List of rules:
        [ ] password.cred
        [ ] password.password
        [x] password.pwd
        [ ] password.pass
List of rules:
        [ ] password.cred
        [x] password.password
        [x] password.pwd
        [ ] password.pass
List of rules:
        [x] password.password
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
Found Secrets: 1
        pwdviolation00.txt:1
            - Metadata:
              status: {staged {false}}
            - Rule:
              password.password
            - Content:
              password = 'this is super secret'
Please remove discovered secrets
```

4) when checking staged changes when there is a staged file w/ a violation added after another file with a violation

```
  should detect 2 violation
  /Users/jamesscott/Development/Workspaces/seekret-git-ws-fork/src/github.com/apuigsech/git-seekret/main_test.go:199
Initialized empty Git repository in /private/var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo946776091/.git/
STEP: creating the SEEKRET_RULES_PATH folder
STEP: setting the SEEKRET_RULES_PATH
STEP: calling the config --init and checking the output
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo151224510
        rulesenabled =
        exceptionsfile =
STEP: checking the local git config
STEP: calling config again, it should just print out the config again.
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo151224510
        rulesenabled =
        exceptionsfile =
List of rules:
        [ ] password.password
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
List of rules:
        [ ] password.pass
        [ ] password.cred
        [x] password.password
        [x] password.pwd
List of rules:
        [x] password.password
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
Found Secrets: 1
        pwdviolation00.txt:1
            - Metadata:
              status: {staged {false}}
            - Rule:
              password.password
            - Content:
              password = 'this is super secret'
Please remove discovered secrets
Found Secrets: 2
        pwdviolation00.txt:1
            - Metadata:
              status: {staged {false}}
            - Rule:
              password.password
            - Content:
              password = 'this is super secret'
        pwdviolation01.txt:1
            - Metadata:
              status: {staged {false}}
            - Rule:
              password.password
            - Content:
              password = 'this is super secret'
Please remove discovered secrets
```
## 5 Hook

1) when the hook is not enabled

```
  should not detect a violation when committing a bad file
  /Users/jamesscott/Development/Workspaces/seekret-git-ws-fork/src/github.com/apuigsech/git-seekret/main_test.go:227
Initialized empty Git repository in /private/var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo382087135/.git/
STEP: creating the SEEKRET_RULES_PATH folder
STEP: setting the SEEKRET_RULES_PATH
STEP: calling the config --init and checking the output
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo974566322
        rulesenabled =
        exceptionsfile =
STEP: checking the local git config
STEP: calling config again, it should just print out the config again.
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo974566322
        rulesenabled =
        exceptionsfile =
List of rules:
        [ ] password.cred
        [ ] password.password
        [x] password.pwd
        [ ] password.pass
List of rules:
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
        [x] password.password
List of rules:
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
        [x] password.password
[master (root-commit) 1bc5cf9] test
 1 file changed, 1 insertion(+)
 create mode 100644 pwdviolation00.txt
```

2) when the hook is enabled

```
  should detect a violation when committing a bad file
  /Users/jamesscott/Development/Workspaces/seekret-git-ws-fork/src/github.com/apuigsech/git-seekret/main_test.go:238
Initialized empty Git repository in /private/var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo887701865/.git/
STEP: creating the SEEKRET_RULES_PATH folder
STEP: setting the SEEKRET_RULES_PATH
STEP: calling the config --init and checking the output
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo066933172
        rulesenabled =
        exceptionsfile =
STEP: checking the local git config
STEP: calling config again, it should just print out the config again.
Config:
        version = 1
        rulespath = /var/folders/n8/xz9pdps11sd7brvz9k3pbps40000gp/T/repo066933172
        rulesenabled =
        exceptionsfile =
List of rules:
        [ ] password.cred
        [ ] password.password
        [x] password.pwd
        [ ] password.pass
List of rules:
        [x] password.password
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
List of rules:
        [x] password.password
        [x] password.pwd
        [ ] password.pass
        [ ] password.cred
Found Secrets: 1
        pwdviolation00.txt:1
            - Metadata:
              status: {staged {false}}
            - Rule:
              password.password
            - Content:
              password = 'this is super secret'
commit cannot proceed
```

### CODE REVIEW

**Comment by jcscottiii** [comment]
@apuigsech any idea on when you will look at this one?

**Comment by apuigsech** [comment]
I am working in some changes into the output of git seekret, and also working on having a interactive check option (that fills automatically the exceptions file). 

I am not ignoring this great work :)

**Comment by jcscottiii** [comment]
@apuigsech there may be a library you already have in mind for interactive selection. If you don't, a new one was announced in the [Golang Weekly](http://golangweekly.com/) newsletter: https://github.com/robbiev/dilemma

I want some examples of how to test that library and reached out the author to see if he could do it.
https://github.com/robbiev/dilemma/issues

I haven't evaluated it at all. So I'm not sure if you can do multiple selection in it.

**Comment by apuigsech** [comment]
I didn't know dilemma but I like it! 

I started to do something like terminal questions and answers oriented using github.com/Songmu/prompter, but I'll reconsider it. Yes, I will need multiple selection for a proper UX.

**Comment by jcscottiii** [comment]
I rebased it just in case you decided to merge it early :)

(it had to be rebased and some conflicts had to be resolved after recent additions to master)

**Comment by jcscottiii** [comment]
There has been a regression somewhere which will cause some of these tests to fail. However, there's a PR #23 which will solve the regression and you can just re-run the tests.

**Comment by apuigsech** [comment]
The interactive checking is taking too much time, because I am quite busy doing other things. So I will merge this PR this weekend.

**Pull request closed without merging**
